### ISSUE TITLE
Crash on context menu "Add element"

### ISSUE THREAD

**Issue by derfenix** [ita1024/semantik#53]
Application: semantik (0.9.4)
KDE Platform Version: 4.14.8
Qt Version: 4.8.6
Operating System: Linux 4.0.4-1-desktop x86_64
Distribution: "openSUSE 20150524 (Tumbleweed) (x86_64)"

-- Information about the crash:
Just press "Add element" in context menu. Adding element by double click works fine.

The crash can be reproduced every time.

```
-- Backtrace:
Application: Semantik (semantik), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[KCrash Handler]
#5  mem_sel::mem_sel (this=0x13aa040, mod=<optimized out>) at ../src/base/mem_base.cpp:120
#6  0x00007f8ff181d99c in mem_add::init (this=this@entry=0x1102650) at ../src/base/mem_base.cpp:238
#7  0x000000000043cc3d in canvas_view::slot_add_item (this=0xeb55e0) at ../src/canvas_view.cpp:431
#8  0x00007f8ff148a20a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib64/libQtCore.so.4
#9  0x00007f8ff08086c2 in QAction::triggered(bool) () from /usr/lib64/libQtGui.so.4
#10 0x00007f8ff080a073 in QAction::activate(QAction::ActionEvent) () from /usr/lib64/libQtGui.so.4
#11 0x00007f8ff0c333a9 in ?? () from /usr/lib64/libQtGui.so.4
#12 0x00007f8ff0c378f9 in ?? () from /usr/lib64/libQtGui.so.4
#13 0x00007f8ff085dcaa in QWidget::event(QEvent*) () from /usr/lib64/libQtGui.so.4
#14 0x00007f8ff0c3b75b in QMenu::event(QEvent*) () from /usr/lib64/libQtGui.so.4
#15 0x00007f8ff080e80c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
#16 0x00007f8ff0814e8a in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
#17 0x00007f8fed2e0dba in KApplication::notify(QObject*, QEvent*) () from /usr/lib64/libkdeui.so.5
#18 0x00007f8ff14762bd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/libQtCore.so.4
#19 0x00007f8ff0814683 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib64/libQtGui.so.4
#20 0x00007f8ff088606c in ?? () from /usr/lib64/libQtGui.so.4
#21 0x00007f8ff08847ac in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib64/libQtGui.so.4
#22 0x00007f8ff08ab652 in ?? () from /usr/lib64/libQtGui.so.4
#23 0x00007f8feb57fc74 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#24 0x00007f8feb57fec8 in ?? () from /usr/lib64/libglib-2.0.so.0
#25 0x00007f8feb57ff6c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#26 0x00007f8ff14a30ce in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#27 0x00007f8ff08ab706 in ?? () from /usr/lib64/libQtGui.so.4
#28 0x00007f8ff1474e7f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#29 0x00007f8ff1475175 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#30 0x00007f8ff147a5c9 in QCoreApplication::exec() () from /usr/lib64/libQtCore.so.4
#31 0x000000000042ee4a in main (i_iArgc=<optimized out>, i_iArgv=0x7ffc7717bd58) at ../src/main.cpp:72
```

**Comment by ita1024** [comment]
Silly mistake. Try a44064c4d4a540777805a7370e7925faea30bb08

**Comment by derfenix** [comment]
Yes, everything work fine now. Thanks!
